Sprint1/step2
AndreyMirenkov/stellar-burgers pull request #2
Opened 2022-11-04 18:05 UTC by AndreyMirenkov

2022-11-05 10:09 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец!**

### **Но есть несколько замечаний, которые нужно исправить:**

- Поправить логику работы у модальных окон.

- Не стоит писать стили инлайново, в будущем это может затруднить поиск ошибок, и перебить стили заданные классами. Лучше дать какой-то класс, и там указать уже нужные вам стили.

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

2022-11-05 10:09 UTC, ArslanMustafin commented on src/utils/api.js
> +    return fetch(`${BASE_URL}`, {
**Можно лучше:** т.к у нас будет много запросов, то лучше вынести в константу только часть url, а другую добавлять в каждом запросе:

```js

export const BASE_URL = 'https://norma.nomoreparties.space/api';

// `${BASE_URL}/ingredients`
```

2022-11-05 10:09 UTC, ArslanMustafin commented on src/components/app/app.js
> +  getInfo()
**Надо исправить:** 

по чек-листу: цепочка обработки промисов завершается блоком `catch`.

2022-11-05 10:09 UTC, ArslanMustafin commented on src/components/app/app.js
> +    document.addEventListener('keydown', modalCloseByEscape);
**Надо исправить:**
Здесь и далее.
Закрытие попапа по ESC относится к функционалу модального окна и должно быть описано в компоненте Modal, вешайте обработчик при открытии (монтировании) и удаляйте закрытии (размонтировании) применив useEffect.

2022-11-05 10:09 UTC, ArslanMustafin commented on src/components/app/app.js
> +  const [visibleIngredientDetails, setVisibleIngredientDetails] = useState(false);
**Можно лучше:** нам не нужна данная переменная, т.к. у нас уже есть переменная `selectedIngredient`. С помощью неё можно проверять. Если в переменной что-то есть, то показываем, если нет, то не показываем.

2022-11-05 10:09 UTC, ArslanMustafin commented on src/components/app/app.js
> +        <IngredientDetails data = {selectedIngredient} isOpen={visibleIngredientDetails} onClose = {handleCloseModal}/>
**Надо исправить:** 

Модальные окна должны быть в соответствующих компонентах. 

`OrderDetails - BurgerConstructor`
`IngredientDetails - BurgerIngredients`.

Не нужно передавать условие открытия в попап и размещать логику открытия там. Рендерите компонент попапа только, если он открыт, используя для этого условный рендеринг. 

Ниже описал, оптимальную структуру, как должно вызываться модальное окно. 

```js
{isOpen && (
  <Popup onClose={onClose}>
    {/** компонент внутри попапа: (IngredientDetails или OrderDetails) */}
  </Popup>
)}
```

2022-11-05 10:09 UTC, ArslanDev666 commented on src/components/ingredient-details/ingredient-details.js
> +    data: dataPropTypes,
**Надо исправить**

в описании propTypes этого и других компонентов нужно указывать .isRequired у пропсов, без этого не контролируется, что пропс передается

Проверьте во всем проекте

2022-11-05 10:09 UTC, ArslanDev666 commented on src/components/ingredient-details/ingredient-details.js
> +        <div style={{overflow: 'hidden'}}>
**Надо исправить:**

Не стоит писать стили инлайново, в будущем это может затруднить поиск ошибок, и перебить стили заданные классами. Лучше дать какой-то класс, и там указать уже нужные вам стили. Исправьте это замечание и в других местах.

2022-11-05 10:09 UTC, ArslanDev666 commented on src/components/modal/modal.js
> +            <ModalOverlay onClose={onClose}/>
**Можно лучше:** Вот такая структура намного больше подходит, и её легче контролировать (не нужно думать о всплытии событий).

```js
<>
 <div className={styles.modal}> {/** ... */} </div>
 <ModalOverlay onClick={onClose} />
</>
```

2022-11-06 04:56 UTC, ArslanDev666 commented on src/components/ingredient-details/ingredient-details.js
> +    const dataIngredient = ({...data});
**Можно лучше:** не совсем понял зачем ещё раз делать из этого объект.

2022-11-06 05:20 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец!**

### **Но есть несколько замечаний, которые нужно исправить:**

- Исправить ошибку в консоли: https://yadi.sk/d/3dzAPe9I8W3ljg.

- В приложении не должно быть консоль логов, и дебаггеров.

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

2022-11-06 05:20 UTC, ArslanMustafin commented on src/components/burger-ingredients/burger-ingredients.js
> +    elPopup: dataPropTypes.isRequired,
**Надо исправить:** Тут вам нужно у этого пропса убрать `isRequired`. Из-за этого возникает такая ошибка в косноли: https://yadi.sk/d/3dzAPe9I8W3ljg

2022-11-06 05:20 UTC, ArslanDev666 commented on src/components/app/app.js
> +    console.log(err)
**Надо исправить:** В приложении не должно быть логов и дебаггеров, в данном случае можно поставить alert, а лучше всего говорить об ошибке пользователю через интерфейс.

2022-11-06 05:20 UTC, ArslanDev666 commented on src/components/modal/modal.js
> +    }
**Можно лучше:** Лучше занести это в useEffect, чтобы не ругался eslint) А еще так мы избежим инициализации каждый раз при ререндере.

2022-11-06 05:20 UTC, ArslanDev666 commented on src/components/ingredient-details/ingredient-details.js
> +    const dataIngredient = ({...data});
**Можно лучше:** не совсем понял зачем ещё раз делать из этого объект.

2022-11-07 04:22 UTC, ArslanDev666 approved these changes
## Code Review

Здравствуйте!

Все замечания с прошлого ревью были исправлены.

### **Вы молодец! Работа принята, но нужно будет обязательно исправить замечания которые я отметил, желательно перед отправкой следующего задания.**

### **Надо исправить:**

- Лучше убрать булки из ингредиентов в burger-constructor, их там быть не должно.
  Должна быть только начинка для бургера.

  Вот так можно отделить отдельно булку, и ингредиенты.

  ```js
  // Лучше обернуть в useMemo.

  const bun = data.find((ingredient) => ingredient.type === "bun");
  const ingredients = data.filter((ingredient) => ingredient.type !== "bun");
  ```

  Все ингредиенты должны выводится, используя данные от api, а не статичные, как у вас сейчас реализованы булки в burger-constructor.

### **Сделает код лучше:**

- Перед отправкой работы убедитесь в том, что весь неиспользуемый код удален.

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders

2022-11-07 04:22 UTC, ArslanDev666 commented on src/components/burger-constructor/burger-constructor.js
> +const priceArray = useMemo(() => data.map(item => item.price), [data]);
**Надо исправить:** 

У вас не правильно считаеться сумма, вы не учитываете булки в количестве 2 штук.

2022-11-07 04:22 UTC, ArslanDev666 commented on src/components/burger-constructor/burger-constructor.js
> +                </div>
**Надо исправить:** 

Все ингредиенты должны выводится, используя данные от api, а не статичные.

2022-12-04 19:50 UTC, merged